
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yufispqpohfratpgrzde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1ZmlzcHFwb2hmcmF0cGdyemRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNDQwMDAsImV4cCI6MjA2MDYyMDAwMH0.hh798vRDnE57LXAW5e--hCoCAg1uUzJ8fXVWkmbvWE8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true
  }
});
